Kseniya/TrackJS - Cannot read property 'width' of undefined
binary-com/SmartCharts pull request #1147
Opened 2021-01-21 15:03 UTC by kseniya-deriv

2021-01-25 07:26 UTC, shayan-binary-2 commented on chartiq/development/js/chartiq.js
> +	if (!this.useBackingStore || !this.backing) return;
@kseniya-deriv the `chartiq` library comes from a 3rd party library so we cannot change its code directly. we modify the chartiq code using code injection or monkey patching, you can find injections in `src/chartiq_injections/backingStore.js`

2021-01-25 07:26 UTC, shayan-binary-2 requested changes
we need to use injection beside changing the code directly

2021-01-25 12:38 UTC, shayan-binary-2 commented on src/chartiq_injections/backingStore.js
> +        if (!this.useBackingStore || !this.backing) return;
@kseniya-deriv just to make a more clear, it's better to put a note here that we changed this line.

2021-01-25 12:39 UTC, shayan-binary-2 approved these changes

2021-01-29 11:20 UTC, carol-binary approved these changes

2021-02-05 02:20 UTC, shayan-binary-2 approved these changes

2021-02-05 02:26 UTC, zaki-binary approved these changes

2021-02-05 02:26 UTC, merged