[DTRA]/Ahmad/DTRA-943/save drawing in template
binary-com/SmartCharts pull request #1537
Opened 2024-03-15 09:12 UTC by ahmadtaimoor-deriv

This PR allows to save drawing tools in the templates . So now a user can save drawing tools in addition with crosshair, indicator, chart Type and chart Interval.

2024-03-19 05:45 UTC, akmal-deriv approved these changes

2024-03-19 06:49 UTC, kate-deriv approved these changes

2024-03-19 07:23 UTC, henry-deriv approved these changes

2024-03-19 08:06 UTC, farhan-nurzi-deriv approved these changes

2024-03-19 12:35 UTC, maryia-deriv commented on chart_app/lib/src/add_ons/add_ons_repository.dart
> +    await _prefs!.remove('template_$templateName');
just a question :) it possible to get rid of '!'s by doing the null check?

2024-03-19 12:37 UTC, maryia-deriv requested changes

2024-03-19 12:37 UTC, maryia-deriv commented on src/store/DrawToolsStore.ts
> +    saveTemplate(name:string){
```suggestion
    saveTemplate(name: string){
```
is a space supposed to be there? same for the below occurrences

2024-03-20 02:31 UTC, balakrishna-deriv commented
We should not be saving drawing tools in a template as the y-axis range differs for each symbol. It makes sense to save indicators in a template but not drawing tools.

2024-03-21 04:25 UTC, closed without merging